// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyBeUme83r_SZG6acFBrwUY1Zyfv0bA0ZYk",
  authDomain: "inora-79f33.firebaseapp.com",
  databaseURL: "https://inora-79f33-default-rtdb.firebaseio.com",
  projectId: "inora-79f33",
  storageBucket: "inora-79f33.appspot.com",
  messagingSenderId: "605643721092",
  appId: "1:605643721092:web:f7cd3fe8d70d03f85cb5d1",
  measurementId: "G-MDLBSQD9D8"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQs7mYWt-rW4uN52eMTX4cRw0tmaOHOU',
    appId: '1:605643721092:android:4145a59c24b9cd7b5cb5d1',
    messagingSenderId: '605643721092',
    projectId: 'inora-79f33',
    databaseURL: 'https://inora-79f33-default-rtdb.firebaseio.com',
    storageBucket: 'inora-79f33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4n1uQzizDLt8ry4zp3uzXJTpEpP-Le-s',
    appId: '1:605643721092:ios:5112327259228c075cb5d1',
    messagingSenderId: '605643721092',
    projectId: 'inora-79f33',
    databaseURL: 'https://inora-79f33-default-rtdb.firebaseio.com',
    storageBucket: 'inora-79f33.appspot.com',
    iosClientId:
        '605643721092-4ij5j2iv6et6eb9sph9k1djphov8om3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.inora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4n1uQzizDLt8ry4zp3uzXJTpEpP-Le-s',
    appId: '1:605643721092:ios:5112327259228c075cb5d1',
    messagingSenderId: '605643721092',
    projectId: 'inora-79f33',
    databaseURL: 'https://inora-79f33-default-rtdb.firebaseio.com',
    storageBucket: 'inora-79f33.appspot.com',
    iosClientId:
        '605643721092-4ij5j2iv6et6eb9sph9k1djphov8om3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.inora',
  );
}
